type MuxThemePresetColor =
  | string
  | {
      readonly dark: string;
      readonly light: string;
    };

interface MuxThemePresetDocument {
  readonly $schema?: string;
  readonly defs?: Readonly<Record<string, MuxThemePresetColor>>;
  readonly theme: Readonly<Record<string, MuxThemePresetColor>>;
}

export const BUILTIN_MUX_THEME_PRESETS_PART_ONE: Readonly<Record<string, MuxThemePresetDocument>> =
  {
    aura: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: 'purple',
        success: 'cyan',
        error: 'red',
        warning: 'orange',
        info: 'purple',
        text: 'darkFg',
        textMuted: 'darkFgMuted',
        background: 'darkBg',
        backgroundPanel: 'darkBgPanel',
        backgroundElement: 'darkBgPanel',
        syntaxFunction: 'purple',
      },
      defs: {
        darkBg: '#0f0f0f',
        darkBgPanel: '#15141b',
        darkBorder: '#2d2d2d',
        darkFgMuted: '#6d6d6d',
        darkFg: '#edecee',
        purple: '#a277ff',
        pink: '#f694ff',
        blue: '#82e2ff',
        red: '#ff6767',
        orange: '#ffca85',
        cyan: '#61ffca',
        green: '#9dff65',
      },
    },
    ayu: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: 'darkEntity',
        success: 'darkAdded',
        error: 'darkError',
        warning: 'darkSpecial',
        info: 'darkTag',
        text: 'darkFg',
        textMuted: 'darkFgMuted',
        background: 'darkBg',
        backgroundPanel: 'darkPanel',
        backgroundElement: 'darkBgAlt',
        syntaxFunction: 'darkFunc',
      },
      defs: {
        darkBg: '#0B0E14',
        darkBgAlt: '#0D1017',
        darkLine: '#11151C',
        darkPanel: '#0F131A',
        darkFg: '#BFBDB6',
        darkFgMuted: '#565B66',
        darkGutter: '#6C7380',
        darkTag: '#39BAE6',
        darkFunc: '#FFB454',
        darkEntity: '#59C2FF',
        darkString: '#AAD94C',
        darkRegexp: '#95E6CB',
        darkMarkup: '#F07178',
        darkKeyword: '#FF8F40',
        darkSpecial: '#E6B673',
        darkComment: '#ACB6BF',
        darkConstant: '#D2A6FF',
        darkOperator: '#F29668',
        darkAdded: '#7FD962',
        darkRemoved: '#F26D78',
        darkAccent: '#E6B450',
        darkError: '#D95757',
        darkIndentActive: '#6C7380',
      },
    },
    carbonfox: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'cyan',
          light: 'blueLight',
        },
        success: {
          dark: 'green',
          light: 'greenLight',
        },
        error: {
          dark: 'red',
          light: 'redLight',
        },
        warning: {
          dark: 'warning',
          light: 'yellowLight',
        },
        info: {
          dark: 'blue',
          light: 'blueLight',
        },
        text: {
          dark: 'fg1',
          light: 'lfg1',
        },
        textMuted: {
          dark: 'fg3',
          light: 'lfg3',
        },
        background: {
          dark: 'bg1',
          light: 'lbg0',
        },
        backgroundPanel: {
          dark: 'bg1a',
          light: 'lbg1',
        },
        backgroundElement: {
          dark: 'bg2',
          light: 'lbg1',
        },
        syntaxFunction: {
          dark: 'blueBright',
          light: 'blueLight',
        },
      },
      defs: {
        bg0: '#0d0d0d',
        bg1: '#161616',
        bg1a: '#1a1a1a',
        bg2: '#1e1e1e',
        bg3: '#262626',
        bg4: '#303030',
        fg0: '#ffffff',
        fg1: '#f2f4f8',
        fg2: '#a9afbc',
        fg3: '#7d848f',
        lbg0: '#ffffff',
        lbg1: '#f4f4f4',
        lbg2: '#e8e8e8',
        lbg3: '#dcdcdc',
        lfg0: '#000000',
        lfg1: '#161616',
        lfg2: '#525252',
        lfg3: '#6f6f6f',
        red: '#ee5396',
        green: '#25be6a',
        yellow: '#08bdba',
        blue: '#78a9ff',
        magenta: '#be95ff',
        cyan: '#33b1ff',
        white: '#dfdfe0',
        orange: '#3ddbd9',
        pink: '#ff7eb6',
        blueBright: '#8cb6ff',
        cyanBright: '#52c7ff',
        greenBright: '#46c880',
        redLight: '#9f1853',
        greenLight: '#198038',
        yellowLight: '#007d79',
        blueLight: '#0043ce',
        magentaLight: '#6929c4',
        cyanLight: '#0072c3',
        warning: '#f1c21b',
        diffGreen: '#50fa7b',
        diffRed: '#ff6b6b',
        diffGreenBg: '#0f2418',
        diffRedBg: '#2a1216',
      },
    },
    catppuccin: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
        success: {
          dark: 'darkGreen',
          light: 'lightGreen',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkYellow',
          light: 'lightYellow',
        },
        info: {
          dark: 'darkTeal',
          light: 'lightTeal',
        },
        text: {
          dark: 'darkText',
          light: 'lightText',
        },
        textMuted: {
          dark: 'darkSubtext1',
          light: 'lightSubtext1',
        },
        background: {
          dark: 'darkBase',
          light: 'lightBase',
        },
        backgroundPanel: {
          dark: 'darkMantle',
          light: 'lightMantle',
        },
        backgroundElement: {
          dark: 'darkCrust',
          light: 'lightCrust',
        },
        syntaxFunction: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
      },
      defs: {
        lightRosewater: '#dc8a78',
        lightFlamingo: '#dd7878',
        lightPink: '#ea76cb',
        lightMauve: '#8839ef',
        lightRed: '#d20f39',
        lightMaroon: '#e64553',
        lightPeach: '#fe640b',
        lightYellow: '#df8e1d',
        lightGreen: '#40a02b',
        lightTeal: '#179299',
        lightSky: '#04a5e5',
        lightSapphire: '#209fb5',
        lightBlue: '#1e66f5',
        lightLavender: '#7287fd',
        lightText: '#4c4f69',
        lightSubtext1: '#5c5f77',
        lightSubtext0: '#6c6f85',
        lightOverlay2: '#7c7f93',
        lightOverlay1: '#8c8fa1',
        lightOverlay0: '#9ca0b0',
        lightSurface2: '#acb0be',
        lightSurface1: '#bcc0cc',
        lightSurface0: '#ccd0da',
        lightBase: '#eff1f5',
        lightMantle: '#e6e9ef',
        lightCrust: '#dce0e8',
        darkRosewater: '#f5e0dc',
        darkFlamingo: '#f2cdcd',
        darkPink: '#f5c2e7',
        darkMauve: '#cba6f7',
        darkRed: '#f38ba8',
        darkMaroon: '#eba0ac',
        darkPeach: '#fab387',
        darkYellow: '#f9e2af',
        darkGreen: '#a6e3a1',
        darkTeal: '#94e2d5',
        darkSky: '#89dceb',
        darkSapphire: '#74c7ec',
        darkBlue: '#89b4fa',
        darkLavender: '#b4befe',
        darkText: '#cdd6f4',
        darkSubtext1: '#bac2de',
        darkSubtext0: '#a6adc8',
        darkOverlay2: '#9399b2',
        darkOverlay1: '#7f849c',
        darkOverlay0: '#6c7086',
        darkSurface2: '#585b70',
        darkSurface1: '#45475a',
        darkSurface0: '#313244',
        darkBase: '#1e1e2e',
        darkMantle: '#181825',
        darkCrust: '#11111b',
      },
    },
    'catppuccin-frappe': {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'frappeBlue',
          light: 'frappeBlue',
        },
        success: {
          dark: 'frappeGreen',
          light: 'frappeGreen',
        },
        error: {
          dark: 'frappeRed',
          light: 'frappeRed',
        },
        warning: {
          dark: 'frappeYellow',
          light: 'frappeYellow',
        },
        info: {
          dark: 'frappeTeal',
          light: 'frappeTeal',
        },
        text: {
          dark: 'frappeText',
          light: 'frappeText',
        },
        textMuted: {
          dark: 'frappeSubtext1',
          light: 'frappeSubtext1',
        },
        background: {
          dark: 'frappeBase',
          light: 'frappeBase',
        },
        backgroundPanel: {
          dark: 'frappeMantle',
          light: 'frappeMantle',
        },
        backgroundElement: {
          dark: 'frappeCrust',
          light: 'frappeCrust',
        },
        syntaxFunction: {
          dark: 'frappeBlue',
          light: 'frappeBlue',
        },
      },
      defs: {
        frappeRosewater: '#f2d5cf',
        frappeFlamingo: '#eebebe',
        frappePink: '#f4b8e4',
        frappeMauve: '#ca9ee6',
        frappeRed: '#e78284',
        frappeMaroon: '#ea999c',
        frappePeach: '#ef9f76',
        frappeYellow: '#e5c890',
        frappeGreen: '#a6d189',
        frappeTeal: '#81c8be',
        frappeSky: '#99d1db',
        frappeSapphire: '#85c1dc',
        frappeBlue: '#8da4e2',
        frappeLavender: '#babbf1',
        frappeText: '#c6d0f5',
        frappeSubtext1: '#b5bfe2',
        frappeSubtext0: '#a5adce',
        frappeOverlay2: '#949cb8',
        frappeOverlay1: '#838ba7',
        frappeOverlay0: '#737994',
        frappeSurface2: '#626880',
        frappeSurface1: '#51576d',
        frappeSurface0: '#414559',
        frappeBase: '#303446',
        frappeMantle: '#292c3c',
        frappeCrust: '#232634',
      },
    },
    'catppuccin-macchiato': {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'macBlue',
          light: 'macBlue',
        },
        success: {
          dark: 'macGreen',
          light: 'macGreen',
        },
        error: {
          dark: 'macRed',
          light: 'macRed',
        },
        warning: {
          dark: 'macYellow',
          light: 'macYellow',
        },
        info: {
          dark: 'macTeal',
          light: 'macTeal',
        },
        text: {
          dark: 'macText',
          light: 'macText',
        },
        textMuted: {
          dark: 'macSubtext1',
          light: 'macSubtext1',
        },
        background: {
          dark: 'macBase',
          light: 'macBase',
        },
        backgroundPanel: {
          dark: 'macMantle',
          light: 'macMantle',
        },
        backgroundElement: {
          dark: 'macCrust',
          light: 'macCrust',
        },
        syntaxFunction: {
          dark: 'macBlue',
          light: 'macBlue',
        },
      },
      defs: {
        macRosewater: '#f4dbd6',
        macFlamingo: '#f0c6c6',
        macPink: '#f5bde6',
        macMauve: '#c6a0f6',
        macRed: '#ed8796',
        macMaroon: '#ee99a0',
        macPeach: '#f5a97f',
        macYellow: '#eed49f',
        macGreen: '#a6da95',
        macTeal: '#8bd5ca',
        macSky: '#91d7e3',
        macSapphire: '#7dc4e4',
        macBlue: '#8aadf4',
        macLavender: '#b7bdf8',
        macText: '#cad3f5',
        macSubtext1: '#b8c0e0',
        macSubtext0: '#a5adcb',
        macOverlay2: '#939ab7',
        macOverlay1: '#8087a2',
        macOverlay0: '#6e738d',
        macSurface2: '#5b6078',
        macSurface1: '#494d64',
        macSurface0: '#363a4f',
        macBase: '#24273a',
        macMantle: '#1e2030',
        macCrust: '#181926',
      },
    },
    cobalt2: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'blue',
          light: '#0066cc',
        },
        success: {
          dark: 'green',
          light: '#4caf50',
        },
        error: {
          dark: 'red',
          light: '#e91e63',
        },
        warning: {
          dark: 'yellow',
          light: '#ff9800',
        },
        info: {
          dark: 'orange',
          light: '#ff5722',
        },
        text: {
          dark: 'foreground',
          light: '#193549',
        },
        textMuted: {
          dark: 'foregroundMuted',
          light: '#5c6b7d',
        },
        background: {
          dark: '#193549',
          light: '#ffffff',
        },
        backgroundPanel: {
          dark: '#122738',
          light: '#f5f7fa',
        },
        backgroundElement: {
          dark: '#1f4662',
          light: '#e8ecf1',
        },
        syntaxFunction: {
          dark: 'yellow',
          light: '#ff9800',
        },
      },
      defs: {
        background: '#193549',
        backgroundAlt: '#122738',
        backgroundPanel: '#1f4662',
        foreground: '#ffffff',
        foregroundMuted: '#adb7c9',
        yellow: '#ffc600',
        yellowBright: '#ffe14c',
        orange: '#ff9d00',
        orangeBright: '#ffb454',
        mint: '#2affdf',
        mintBright: '#7efff5',
        blue: '#0088ff',
        blueBright: '#5cb7ff',
        pink: '#ff628c',
        pinkBright: '#ff86a5',
        green: '#9eff80',
        greenBright: '#b9ff9f',
        purple: '#9a5feb',
        purpleBright: '#b88cfd',
        red: '#ff0088',
        redBright: '#ff5fb3',
      },
    },
    cursor: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkCyan',
          light: 'lightTeal',
        },
        success: {
          dark: 'darkGreen',
          light: 'lightGreen',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkYellow',
          light: 'lightOrange',
        },
        info: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
        text: {
          dark: 'darkFg',
          light: 'lightFg',
        },
        textMuted: {
          dark: 'darkMuted',
          light: 'lightMuted',
        },
        background: {
          dark: 'darkBg',
          light: 'lightBg',
        },
        backgroundPanel: {
          dark: 'darkPanel',
          light: 'lightPanel',
        },
        backgroundElement: {
          dark: 'darkElement',
          light: 'lightElement',
        },
        syntaxFunction: {
          dark: 'darkSyntaxOrange',
          light: 'lightOrange',
        },
      },
      defs: {
        darkBg: '#181818',
        darkPanel: '#141414',
        darkElement: '#262626',
        darkFg: '#e4e4e4',
        darkMuted: '#e4e4e45e',
        darkBorder: '#e4e4e413',
        darkBorderActive: '#e4e4e426',
        darkCyan: '#88c0d0',
        darkBlue: '#81a1c1',
        darkGreen: '#3fa266',
        darkGreenBright: '#70b489',
        darkRed: '#e34671',
        darkRedBright: '#fc6b83',
        darkYellow: '#f1b467',
        darkOrange: '#d2943e',
        darkPink: '#E394DC',
        darkPurple: '#AAA0FA',
        darkTeal: '#82D2CE',
        darkSyntaxYellow: '#F8C762',
        darkSyntaxOrange: '#EFB080',
        darkSyntaxGreen: '#A8CC7C',
        darkSyntaxBlue: '#87C3FF',
        lightBg: '#fcfcfc',
        lightPanel: '#f3f3f3',
        lightElement: '#ededed',
        lightFg: '#141414',
        lightMuted: '#141414ad',
        lightBorder: '#14141413',
        lightBorderActive: '#14141426',
        lightTeal: '#6f9ba6',
        lightBlue: '#3c7cab',
        lightBlueDark: '#206595',
        lightGreen: '#1f8a65',
        lightGreenBright: '#55a583',
        lightRed: '#cf2d56',
        lightRedBright: '#e75e78',
        lightOrange: '#db704b',
        lightYellow: '#c08532',
        lightPurple: '#9e94d5',
        lightPurpleDark: '#6049b3',
        lightPink: '#b8448b',
        lightMagenta: '#b3003f',
      },
    },
    dracula: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'purple',
          light: 'purple',
        },
        success: {
          dark: 'green',
          light: 'green',
        },
        error: {
          dark: 'red',
          light: 'red',
        },
        warning: {
          dark: 'yellow',
          light: 'yellow',
        },
        info: {
          dark: 'orange',
          light: 'orange',
        },
        text: {
          dark: 'foreground',
          light: '#282a36',
        },
        textMuted: {
          dark: 'comment',
          light: '#6272a4',
        },
        background: {
          dark: '#282a36',
          light: '#f8f8f2',
        },
        backgroundPanel: {
          dark: '#21222c',
          light: '#e8e8e2',
        },
        backgroundElement: {
          dark: 'currentLine',
          light: '#d8d8d2',
        },
        syntaxFunction: {
          dark: 'green',
          light: 'green',
        },
      },
      defs: {
        background: '#282a36',
        currentLine: '#44475a',
        selection: '#44475a',
        foreground: '#f8f8f2',
        comment: '#6272a4',
        cyan: '#8be9fd',
        green: '#50fa7b',
        orange: '#ffb86c',
        pink: '#ff79c6',
        purple: '#bd93f9',
        red: '#ff5555',
        yellow: '#f1fa8c',
      },
    },
    everforest: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkStep9',
          light: 'lightStep9',
        },
        success: {
          dark: 'darkGreen',
          light: 'lightGreen',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkOrange',
          light: 'lightOrange',
        },
        info: {
          dark: 'darkCyan',
          light: 'lightCyan',
        },
        text: {
          dark: 'darkStep12',
          light: 'lightStep12',
        },
        textMuted: {
          dark: 'darkStep11',
          light: 'lightStep11',
        },
        background: {
          dark: 'darkStep1',
          light: 'lightStep1',
        },
        backgroundPanel: {
          dark: 'darkStep2',
          light: 'lightStep2',
        },
        backgroundElement: {
          dark: 'darkStep3',
          light: 'lightStep3',
        },
        syntaxFunction: {
          dark: 'darkStep9',
          light: 'lightStep9',
        },
      },
      defs: {
        darkStep1: '#2d353b',
        darkStep2: '#333c43',
        darkStep3: '#343f44',
        darkStep4: '#3d484d',
        darkStep5: '#475258',
        darkStep6: '#7a8478',
        darkStep7: '#859289',
        darkStep8: '#9da9a0',
        darkStep9: '#a7c080',
        darkStep10: '#83c092',
        darkStep11: '#7a8478',
        darkStep12: '#d3c6aa',
        darkRed: '#e67e80',
        darkOrange: '#e69875',
        darkGreen: '#a7c080',
        darkCyan: '#83c092',
        darkYellow: '#dbbc7f',
        lightStep1: '#fdf6e3',
        lightStep2: '#efebd4',
        lightStep3: '#f4f0d9',
        lightStep4: '#efebd4',
        lightStep5: '#e6e2cc',
        lightStep6: '#a6b0a0',
        lightStep7: '#939f91',
        lightStep8: '#829181',
        lightStep9: '#8da101',
        lightStep10: '#35a77c',
        lightStep11: '#a6b0a0',
        lightStep12: '#5c6a72',
        lightRed: '#f85552',
        lightOrange: '#f57d26',
        lightGreen: '#8da101',
        lightCyan: '#35a77c',
        lightYellow: '#dfa000',
      },
    },
    flexoki: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'orange400',
          light: 'blue600',
        },
        success: {
          dark: 'green400',
          light: 'green600',
        },
        error: {
          dark: 'red400',
          light: 'red600',
        },
        warning: {
          dark: 'orange400',
          light: 'orange600',
        },
        info: {
          dark: 'cyan400',
          light: 'cyan600',
        },
        text: {
          dark: 'base200',
          light: 'black',
        },
        textMuted: {
          dark: 'base600',
          light: 'base600',
        },
        background: {
          dark: 'black',
          light: 'paper',
        },
        backgroundPanel: {
          dark: 'base950',
          light: 'base50',
        },
        backgroundElement: {
          dark: 'base900',
          light: 'base100',
        },
        syntaxFunction: {
          dark: 'orange400',
          light: 'orange600',
        },
      },
      defs: {
        black: '#100F0F',
        base950: '#1C1B1A',
        base900: '#282726',
        base850: '#343331',
        base800: '#403E3C',
        base700: '#575653',
        base600: '#6F6E69',
        base500: '#878580',
        base300: '#B7B5AC',
        base200: '#CECDC3',
        base150: '#DAD8CE',
        base100: '#E6E4D9',
        base50: '#F2F0E5',
        paper: '#FFFCF0',
        red400: '#D14D41',
        red600: '#AF3029',
        orange400: '#DA702C',
        orange600: '#BC5215',
        yellow400: '#D0A215',
        yellow600: '#AD8301',
        green400: '#879A39',
        green600: '#66800B',
        cyan400: '#3AA99F',
        cyan600: '#24837B',
        blue400: '#4385BE',
        blue600: '#205EA6',
        purple400: '#8B7EC8',
        purple600: '#5E409D',
        magenta400: '#CE5D97',
        magenta600: '#A02F6F',
      },
    },
    github: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
        success: {
          dark: 'darkGreen',
          light: 'lightGreen',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkYellow',
          light: 'lightYellow',
        },
        info: {
          dark: 'darkOrange',
          light: 'lightOrange',
        },
        text: {
          dark: 'darkFg',
          light: 'lightFg',
        },
        textMuted: {
          dark: 'darkFgMuted',
          light: 'lightFgMuted',
        },
        background: {
          dark: 'darkBg',
          light: 'lightBg',
        },
        backgroundPanel: {
          dark: 'darkBgAlt',
          light: 'lightBgAlt',
        },
        backgroundElement: {
          dark: 'darkBgPanel',
          light: 'lightBgPanel',
        },
        syntaxFunction: {
          dark: 'darkPurple',
          light: 'lightPurple',
        },
      },
      defs: {
        darkBg: '#0d1117',
        darkBgAlt: '#010409',
        darkBgPanel: '#161b22',
        darkFg: '#c9d1d9',
        darkFgMuted: '#8b949e',
        darkBlue: '#58a6ff',
        darkGreen: '#3fb950',
        darkRed: '#f85149',
        darkOrange: '#d29922',
        darkPurple: '#bc8cff',
        darkPink: '#ff7b72',
        darkYellow: '#e3b341',
        darkCyan: '#39c5cf',
        lightBg: '#ffffff',
        lightBgAlt: '#f6f8fa',
        lightBgPanel: '#f0f3f6',
        lightFg: '#24292f',
        lightFgMuted: '#57606a',
        lightBlue: '#0969da',
        lightGreen: '#1a7f37',
        lightRed: '#cf222e',
        lightOrange: '#bc4c00',
        lightPurple: '#8250df',
        lightPink: '#bf3989',
        lightYellow: '#9a6700',
        lightCyan: '#1b7c83',
      },
    },
    gruvbox: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkBlueBright',
          light: 'lightBlue',
        },
        success: {
          dark: 'darkGreenBright',
          light: 'lightGreen',
        },
        error: {
          dark: 'darkRedBright',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkOrangeBright',
          light: 'lightOrange',
        },
        info: {
          dark: 'darkYellowBright',
          light: 'lightYellow',
        },
        text: {
          dark: 'darkFg1',
          light: 'lightFg1',
        },
        textMuted: {
          dark: 'darkGray',
          light: 'lightGray',
        },
        background: {
          dark: 'darkBg0',
          light: 'lightBg0',
        },
        backgroundPanel: {
          dark: 'darkBg1',
          light: 'lightBg1',
        },
        backgroundElement: {
          dark: 'darkBg2',
          light: 'lightBg2',
        },
        syntaxFunction: {
          dark: 'darkGreenBright',
          light: 'lightGreen',
        },
      },
      defs: {
        darkBg0: '#282828',
        darkBg1: '#3c3836',
        darkBg2: '#504945',
        darkBg3: '#665c54',
        darkFg0: '#fbf1c7',
        darkFg1: '#ebdbb2',
        darkGray: '#928374',
        darkRed: '#cc241d',
        darkGreen: '#98971a',
        darkYellow: '#d79921',
        darkBlue: '#458588',
        darkPurple: '#b16286',
        darkAqua: '#689d6a',
        darkOrange: '#d65d0e',
        darkRedBright: '#fb4934',
        darkGreenBright: '#b8bb26',
        darkYellowBright: '#fabd2f',
        darkBlueBright: '#83a598',
        darkPurpleBright: '#d3869b',
        darkAquaBright: '#8ec07c',
        darkOrangeBright: '#fe8019',
        lightBg0: '#fbf1c7',
        lightBg1: '#ebdbb2',
        lightBg2: '#d5c4a1',
        lightBg3: '#bdae93',
        lightFg0: '#282828',
        lightFg1: '#3c3836',
        lightGray: '#7c6f64',
        lightRed: '#9d0006',
        lightGreen: '#79740e',
        lightYellow: '#b57614',
        lightBlue: '#076678',
        lightPurple: '#8f3f71',
        lightAqua: '#427b58',
        lightOrange: '#af3a03',
      },
    },
    kanagawa: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'crystalBlue',
          light: 'waveBlue',
        },
        success: {
          dark: 'lotusGreen',
          light: 'lotusGreen',
        },
        error: {
          dark: 'dragonRed',
          light: 'dragonRed',
        },
        warning: {
          dark: 'roninYellow',
          light: 'roninYellow',
        },
        info: {
          dark: 'waveAqua',
          light: 'waveAqua',
        },
        text: {
          dark: 'fujiWhite',
          light: 'lightText',
        },
        textMuted: {
          dark: 'fujiGray',
          light: 'lightGray',
        },
        background: {
          dark: 'sumiInk0',
          light: 'lightBg',
        },
        backgroundPanel: {
          dark: 'sumiInk1',
          light: 'lightPaper',
        },
        backgroundElement: {
          dark: 'sumiInk2',
          light: '#E3DCD2',
        },
        syntaxFunction: {
          dark: 'crystalBlue',
          light: 'waveBlue',
        },
      },
      defs: {
        sumiInk0: '#1F1F28',
        sumiInk1: '#2A2A37',
        sumiInk2: '#363646',
        sumiInk3: '#54546D',
        fujiWhite: '#DCD7BA',
        oldWhite: '#C8C093',
        fujiGray: '#727169',
        oniViolet: '#957FB8',
        crystalBlue: '#7E9CD8',
        carpYellow: '#C38D9D',
        sakuraPink: '#D27E99',
        waveAqua: '#76946A',
        roninYellow: '#D7A657',
        dragonRed: '#E82424',
        lotusGreen: '#98BB6C',
        waveBlue: '#2D4F67',
        lightBg: '#F2E9DE',
        lightPaper: '#EAE4D7',
        lightText: '#54433A',
        lightGray: '#9E9389',
      },
    },
    'lucent-orng': {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkOrange',
          light: 'lightOrange',
        },
        success: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkOrange',
          light: 'lightOrange',
        },
        info: {
          dark: 'darkCyan',
          light: 'lightCyan',
        },
        text: {
          dark: 'darkStep12',
          light: 'lightStep12',
        },
        textMuted: {
          dark: 'darkStep11',
          light: 'lightStep11',
        },
        background: {
          dark: 'transparent',
          light: 'transparent',
        },
        backgroundPanel: {
          dark: 'transparent',
          light: 'transparent',
        },
        backgroundElement: {
          dark: 'transparent',
          light: 'transparent',
        },
        syntaxFunction: {
          dark: 'darkSecondary',
          light: 'lightAccent',
        },
      },
      defs: {
        darkStep6: '#3c3c3c',
        darkStep11: '#808080',
        darkStep12: '#eeeeee',
        darkSecondary: '#EE7948',
        darkAccent: '#FFF7F1',
        darkRed: '#e06c75',
        darkOrange: '#EC5B2B',
        darkBlue: '#6ba1e6',
        darkCyan: '#56b6c2',
        darkYellow: '#e5c07b',
        darkPanelBg: '#2a1a1599',
        lightStep6: '#d4d4d4',
        lightStep11: '#8a8a8a',
        lightStep12: '#1a1a1a',
        lightSecondary: '#EE7948',
        lightAccent: '#c94d24',
        lightRed: '#d1383d',
        lightOrange: '#EC5B2B',
        lightBlue: '#0062d1',
        lightCyan: '#318795',
        lightYellow: '#b0851f',
        lightPanelBg: '#fff5f099',
      },
    },
    material: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
        success: {
          dark: 'darkGreen',
          light: 'lightGreen',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkYellow',
          light: 'lightYellow',
        },
        info: {
          dark: 'darkOrange',
          light: 'lightOrange',
        },
        text: {
          dark: 'darkFg',
          light: 'lightFg',
        },
        textMuted: {
          dark: 'darkFgMuted',
          light: 'lightFgMuted',
        },
        background: {
          dark: 'darkBg',
          light: 'lightBg',
        },
        backgroundPanel: {
          dark: 'darkBgAlt',
          light: 'lightBgAlt',
        },
        backgroundElement: {
          dark: 'darkBgPanel',
          light: 'lightBgPanel',
        },
        syntaxFunction: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
      },
      defs: {
        darkBg: '#263238',
        darkBgAlt: '#1e272c',
        darkBgPanel: '#37474f',
        darkFg: '#eeffff',
        darkFgMuted: '#546e7a',
        darkRed: '#f07178',
        darkPink: '#f78c6c',
        darkOrange: '#ffcb6b',
        darkYellow: '#ffcb6b',
        darkGreen: '#c3e88d',
        darkCyan: '#89ddff',
        darkBlue: '#82aaff',
        darkPurple: '#c792ea',
        darkViolet: '#bb80b3',
        lightBg: '#fafafa',
        lightBgAlt: '#f5f5f5',
        lightBgPanel: '#e7e7e8',
        lightFg: '#263238',
        lightFgMuted: '#90a4ae',
        lightRed: '#e53935',
        lightPink: '#ec407a',
        lightOrange: '#f4511e',
        lightYellow: '#ffb300',
        lightGreen: '#91b859',
        lightCyan: '#39adb5',
        lightBlue: '#6182b8',
        lightPurple: '#7c4dff',
        lightViolet: '#945eb8',
      },
    },
    matrix: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'rainGreen',
          light: 'rainGreenDim',
        },
        success: {
          dark: 'rainGreenHi',
          light: 'rainGreenDim',
        },
        error: {
          dark: 'alertRed',
          light: 'alertRed',
        },
        warning: {
          dark: 'alertYellow',
          light: 'alertYellow',
        },
        info: {
          dark: 'alertBlue',
          light: 'alertBlue',
        },
        text: {
          dark: 'rainGreenHi',
          light: 'lightText',
        },
        textMuted: {
          dark: 'rainGray',
          light: 'lightGray',
        },
        background: {
          dark: 'matrixInk0',
          light: 'lightBg',
        },
        backgroundPanel: {
          dark: 'matrixInk1',
          light: 'lightPaper',
        },
        backgroundElement: {
          dark: 'matrixInk2',
          light: 'lightInk1',
        },
        syntaxFunction: {
          dark: 'alertBlue',
          light: 'alertBlue',
        },
      },
      defs: {
        matrixInk0: '#0a0e0a',
        matrixInk1: '#0e130d',
        matrixInk2: '#141c12',
        matrixInk3: '#1e2a1b',
        rainGreen: '#2eff6a',
        rainGreenDim: '#1cc24b',
        rainGreenHi: '#62ff94',
        rainCyan: '#00efff',
        rainTeal: '#24f6d9',
        rainPurple: '#c770ff',
        rainOrange: '#ffa83d',
        alertRed: '#ff4b4b',
        alertYellow: '#e6ff57',
        alertBlue: '#30b3ff',
        rainGray: '#8ca391',
        lightBg: '#eef3ea',
        lightPaper: '#e4ebe1',
        lightInk1: '#dae1d7',
        lightText: '#203022',
        lightGray: '#748476',
      },
    },
  };
