type MuxThemePresetColor =
  | string
  | {
      readonly dark: string;
      readonly light: string;
    };

interface MuxThemePresetDocument {
  readonly $schema?: string;
  readonly defs?: Readonly<Record<string, MuxThemePresetColor>>;
  readonly theme: Readonly<Record<string, MuxThemePresetColor>>;
}

export const BUILTIN_MUX_THEME_PRESETS_PART_TWO: Readonly<Record<string, MuxThemePresetDocument>> =
  {
    mercury: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          light: 'purple-600',
          dark: 'purple-400',
        },
        success: {
          light: 'green-700',
          dark: 'green-400',
        },
        error: {
          light: 'red-700',
          dark: 'red-400',
        },
        warning: {
          light: 'orange-700',
          dark: 'orange-400',
        },
        info: {
          light: 'blue-600',
          dark: 'blue-400',
        },
        text: {
          light: 'neutral-700',
          dark: 'neutral-200',
        },
        textMuted: {
          light: 'neutral-500',
          dark: 'neutral-400',
        },
        background: {
          light: 'neutral-000',
          dark: 'neutral-950',
        },
        backgroundPanel: {
          light: 'neutral-050',
          dark: 'neutral-1000',
        },
        backgroundElement: {
          light: 'neutral-100',
          dark: 'neutral-800',
        },
        syntaxFunction: {
          light: 'purple-600',
          dark: 'purple-400',
        },
      },
      defs: {
        'purple-800': '#3442a6',
        'purple-700': '#465bd1',
        'purple-600': '#5266eb',
        'purple-400': '#8da4f5',
        'purple-300': '#a7b6f8',
        'red-700': '#b0175f',
        'red-600': '#d03275',
        'red-400': '#fc92b4',
        'green-700': '#036e43',
        'green-600': '#188554',
        'green-400': '#77c599',
        'orange-700': '#a44200',
        'orange-600': '#c45000',
        'orange-400': '#fc9b6f',
        'blue-600': '#007f95',
        'blue-400': '#77becf',
        'neutral-1000': '#10101a',
        'neutral-950': '#171721',
        'neutral-900': '#1e1e2a',
        'neutral-800': '#272735',
        'neutral-700': '#363644',
        'neutral-600': '#535461',
        'neutral-500': '#70707d',
        'neutral-400': '#9d9da8',
        'neutral-300': '#c3c3cc',
        'neutral-200': '#dddde5',
        'neutral-100': '#f4f5f9',
        'neutral-050': '#fbfcfd',
        'neutral-000': '#ffffff',
        'neutral-150': '#ededf3',
        'border-light': '#7073931a',
        'border-light-subtle': '#7073930f',
        'border-dark': '#b4b7c81f',
        'border-dark-subtle': '#b4b7c814',
        'diff-added-light': '#1885541a',
        'diff-removed-light': '#d032751a',
        'diff-added-dark': '#77c59933',
        'diff-removed-dark': '#fc92b433',
      },
    },
    monokai: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'cyan',
          light: 'blue',
        },
        success: {
          dark: 'green',
          light: 'green',
        },
        error: {
          dark: 'red',
          light: 'red',
        },
        warning: {
          dark: 'yellow',
          light: 'orange',
        },
        info: {
          dark: 'orange',
          light: 'orange',
        },
        text: {
          dark: 'foreground',
          light: '#272822',
        },
        textMuted: {
          dark: 'comment',
          light: '#75715e',
        },
        background: {
          dark: '#272822',
          light: '#fafafa',
        },
        backgroundPanel: {
          dark: '#1e1f1c',
          light: '#f0f0f0',
        },
        backgroundElement: {
          dark: '#3e3d32',
          light: '#e0e0e0',
        },
        syntaxFunction: {
          dark: 'green',
          light: 'green',
        },
      },
      defs: {
        background: '#272822',
        backgroundAlt: '#1e1f1c',
        backgroundPanel: '#3e3d32',
        foreground: '#f8f8f2',
        comment: '#75715e',
        red: '#f92672',
        orange: '#fd971f',
        lightOrange: '#e69f66',
        yellow: '#e6db74',
        green: '#a6e22e',
        cyan: '#66d9ef',
        blue: '#66d9ef',
        purple: '#ae81ff',
        pink: '#f92672',
      },
    },
    nightowl: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'nightOwlBlue',
          light: 'nightOwlBlue',
        },
        success: {
          dark: 'nightOwlGreen',
          light: 'nightOwlGreen',
        },
        error: {
          dark: 'nightOwlRed',
          light: 'nightOwlRed',
        },
        warning: {
          dark: 'nightOwlYellow',
          light: 'nightOwlYellow',
        },
        info: {
          dark: 'nightOwlBlue',
          light: 'nightOwlBlue',
        },
        text: {
          dark: 'nightOwlFg',
          light: 'nightOwlFg',
        },
        textMuted: {
          dark: 'nightOwlMuted',
          light: 'nightOwlMuted',
        },
        background: {
          dark: 'nightOwlBg',
          light: 'nightOwlBg',
        },
        backgroundPanel: {
          dark: 'nightOwlPanel',
          light: 'nightOwlPanel',
        },
        backgroundElement: {
          dark: 'nightOwlPanel',
          light: 'nightOwlPanel',
        },
        syntaxFunction: {
          dark: 'nightOwlBlue',
          light: 'nightOwlBlue',
        },
      },
      defs: {
        nightOwlBg: '#011627',
        nightOwlFg: '#d6deeb',
        nightOwlBlue: '#82AAFF',
        nightOwlCyan: '#7fdbca',
        nightOwlGreen: '#c5e478',
        nightOwlYellow: '#ecc48d',
        nightOwlOrange: '#F78C6C',
        nightOwlRed: '#EF5350',
        nightOwlPink: '#ff5874',
        nightOwlPurple: '#c792ea',
        nightOwlMuted: '#5f7e97',
        nightOwlGray: '#637777',
        nightOwlLightGray: '#89a4bb',
        nightOwlPanel: '#0b253a',
      },
    },
    nord: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'nord8',
          light: 'nord10',
        },
        success: {
          dark: 'nord14',
          light: 'nord14',
        },
        error: {
          dark: 'nord11',
          light: 'nord11',
        },
        warning: {
          dark: 'nord12',
          light: 'nord12',
        },
        info: {
          dark: 'nord8',
          light: 'nord10',
        },
        text: {
          dark: 'nord6',
          light: 'nord0',
        },
        textMuted: {
          dark: '#8B95A7',
          light: 'nord1',
        },
        background: {
          dark: 'nord0',
          light: 'nord6',
        },
        backgroundPanel: {
          dark: 'nord1',
          light: 'nord5',
        },
        backgroundElement: {
          dark: 'nord2',
          light: 'nord4',
        },
        syntaxFunction: {
          dark: 'nord8',
          light: 'nord8',
        },
      },
      defs: {
        nord0: '#2E3440',
        nord1: '#3B4252',
        nord2: '#434C5E',
        nord3: '#4C566A',
        nord4: '#D8DEE9',
        nord5: '#E5E9F0',
        nord6: '#ECEFF4',
        nord7: '#8FBCBB',
        nord8: '#88C0D0',
        nord9: '#81A1C1',
        nord10: '#5E81AC',
        nord11: '#BF616A',
        nord12: '#D08770',
        nord13: '#EBCB8B',
        nord14: '#A3BE8C',
        nord15: '#B48EAD',
      },
    },
    'one-dark': {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
        success: {
          dark: 'darkGreen',
          light: 'lightGreen',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkYellow',
          light: 'lightYellow',
        },
        info: {
          dark: 'darkOrange',
          light: 'lightOrange',
        },
        text: {
          dark: 'darkFg',
          light: 'lightFg',
        },
        textMuted: {
          dark: 'darkFgMuted',
          light: 'lightFgMuted',
        },
        background: {
          dark: 'darkBg',
          light: 'lightBg',
        },
        backgroundPanel: {
          dark: 'darkBgAlt',
          light: 'lightBgAlt',
        },
        backgroundElement: {
          dark: 'darkBgPanel',
          light: 'lightBgPanel',
        },
        syntaxFunction: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
      },
      defs: {
        darkBg: '#282c34',
        darkBgAlt: '#21252b',
        darkBgPanel: '#353b45',
        darkFg: '#abb2bf',
        darkFgMuted: '#5c6370',
        darkPurple: '#c678dd',
        darkBlue: '#61afef',
        darkRed: '#e06c75',
        darkGreen: '#98c379',
        darkYellow: '#e5c07b',
        darkOrange: '#d19a66',
        darkCyan: '#56b6c2',
        lightBg: '#fafafa',
        lightBgAlt: '#f0f0f1',
        lightBgPanel: '#eaeaeb',
        lightFg: '#383a42',
        lightFgMuted: '#a0a1a7',
        lightPurple: '#a626a4',
        lightBlue: '#4078f2',
        lightRed: '#e45649',
        lightGreen: '#50a14f',
        lightYellow: '#c18401',
        lightOrange: '#986801',
        lightCyan: '#0184bc',
      },
    },
    opencode: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkStep9',
          light: 'lightStep9',
        },
        success: {
          dark: 'darkGreen',
          light: 'lightGreen',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkOrange',
          light: 'lightOrange',
        },
        info: {
          dark: 'darkCyan',
          light: 'lightCyan',
        },
        text: {
          dark: 'darkStep12',
          light: 'lightStep12',
        },
        textMuted: {
          dark: 'darkStep11',
          light: 'lightStep11',
        },
        background: {
          dark: 'darkStep1',
          light: 'lightStep1',
        },
        backgroundPanel: {
          dark: 'darkStep2',
          light: 'lightStep2',
        },
        backgroundElement: {
          dark: 'darkStep3',
          light: 'lightStep3',
        },
        syntaxFunction: {
          dark: 'darkStep9',
          light: 'lightStep9',
        },
      },
      defs: {
        darkStep1: '#0a0a0a',
        darkStep2: '#141414',
        darkStep3: '#1e1e1e',
        darkStep4: '#282828',
        darkStep5: '#323232',
        darkStep6: '#3c3c3c',
        darkStep7: '#484848',
        darkStep8: '#606060',
        darkStep9: '#fab283',
        darkStep10: '#ffc09f',
        darkStep11: '#808080',
        darkStep12: '#eeeeee',
        darkSecondary: '#5c9cf5',
        darkAccent: '#9d7cd8',
        darkRed: '#e06c75',
        darkOrange: '#f5a742',
        darkGreen: '#7fd88f',
        darkCyan: '#56b6c2',
        darkYellow: '#e5c07b',
        lightStep1: '#ffffff',
        lightStep2: '#fafafa',
        lightStep3: '#f5f5f5',
        lightStep4: '#ebebeb',
        lightStep5: '#e1e1e1',
        lightStep6: '#d4d4d4',
        lightStep7: '#b8b8b8',
        lightStep8: '#a0a0a0',
        lightStep9: '#3b7dd8',
        lightStep10: '#2968c3',
        lightStep11: '#8a8a8a',
        lightStep12: '#1a1a1a',
        lightSecondary: '#7b5bb6',
        lightAccent: '#d68c27',
        lightRed: '#d1383d',
        lightOrange: '#d68c27',
        lightGreen: '#3d9a57',
        lightCyan: '#318795',
        lightYellow: '#b0851f',
      },
    },
    orng: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkStep9',
          light: 'lightStep9',
        },
        success: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkOrange',
          light: 'lightOrange',
        },
        info: {
          dark: 'darkCyan',
          light: 'lightCyan',
        },
        text: {
          dark: 'darkStep12',
          light: 'lightStep12',
        },
        textMuted: {
          dark: 'darkStep11',
          light: 'lightStep11',
        },
        background: {
          dark: 'darkStep1',
          light: 'lightStep1',
        },
        backgroundPanel: {
          dark: 'darkStep2',
          light: 'lightStep2',
        },
        backgroundElement: {
          dark: 'darkStep3',
          light: 'lightStep3',
        },
        syntaxFunction: {
          dark: '#EE7948',
          light: '#c94d24',
        },
      },
      defs: {
        darkStep1: '#0a0a0a',
        darkStep2: '#141414',
        darkStep3: '#1e1e1e',
        darkStep4: '#282828',
        darkStep5: '#323232',
        darkStep6: '#3c3c3c',
        darkStep7: '#484848',
        darkStep8: '#606060',
        darkStep9: '#EC5B2B',
        darkStep10: '#EE7948',
        darkStep11: '#808080',
        darkStep12: '#eeeeee',
        darkSecondary: '#EE7948',
        darkAccent: '#FFF7F1',
        darkRed: '#e06c75',
        darkOrange: '#EC5B2B',
        darkBlue: '#6ba1e6',
        darkCyan: '#56b6c2',
        darkYellow: '#e5c07b',
        lightStep1: '#ffffff',
        lightStep2: '#FFF7F1',
        lightStep3: '#f5f0eb',
        lightStep4: '#ebebeb',
        lightStep5: '#e1e1e1',
        lightStep6: '#d4d4d4',
        lightStep7: '#b8b8b8',
        lightStep8: '#a0a0a0',
        lightStep9: '#EC5B2B',
        lightStep10: '#c94d24',
        lightStep11: '#8a8a8a',
        lightStep12: '#1a1a1a',
        lightSecondary: '#EE7948',
        lightAccent: '#c94d24',
        lightRed: '#d1383d',
        lightOrange: '#EC5B2B',
        lightBlue: '#0062d1',
        lightCyan: '#318795',
        lightYellow: '#b0851f',
      },
    },
    'osaka-jade': {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkCyan',
          light: 'lightCyan',
        },
        success: {
          dark: 'darkGreen',
          light: 'lightGreen',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkYellowBright',
          light: 'lightYellow',
        },
        info: {
          dark: 'darkCyan',
          light: 'lightCyan',
        },
        text: {
          dark: 'darkFg0',
          light: 'lightFg0',
        },
        textMuted: {
          dark: 'darkGray',
          light: 'lightGray',
        },
        background: {
          dark: 'darkBg0',
          light: 'lightBg0',
        },
        backgroundPanel: {
          dark: 'darkBg1',
          light: 'lightBg1',
        },
        backgroundElement: {
          dark: 'darkBg2',
          light: 'lightBg2',
        },
        syntaxFunction: {
          dark: 'darkBlue',
          light: 'lightBlue',
        },
      },
      defs: {
        darkBg0: '#111c18',
        darkBg1: '#1a2520',
        darkBg2: '#23372B',
        darkBg3: '#3d4a44',
        darkFg0: '#C1C497',
        darkFg1: '#9aa88a',
        darkGray: '#53685B',
        darkRed: '#FF5345',
        darkGreen: '#549e6a',
        darkYellow: '#459451',
        darkBlue: '#509475',
        darkMagenta: '#D2689C',
        darkCyan: '#2DD5B7',
        darkWhite: '#F6F5DD',
        darkRedBright: '#db9f9c',
        darkGreenBright: '#63b07a',
        darkYellowBright: '#E5C736',
        darkBlueBright: '#ACD4CF',
        darkMagentaBright: '#75bbb3',
        darkCyanBright: '#8CD3CB',
        lightBg0: '#F6F5DD',
        lightBg1: '#E8E7CC',
        lightBg2: '#D5D4B8',
        lightBg3: '#A8A78C',
        lightFg0: '#111c18',
        lightFg1: '#1a2520',
        lightGray: '#53685B',
        lightRed: '#c7392d',
        lightGreen: '#3d7a52',
        lightYellow: '#b5a020',
        lightBlue: '#3d7560',
        lightMagenta: '#a8527a',
        lightCyan: '#1faa90',
      },
    },
    palenight: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'blue',
          light: '#4976eb',
        },
        success: {
          dark: 'green',
          light: '#91b859',
        },
        error: {
          dark: 'red',
          light: '#e53935',
        },
        warning: {
          dark: 'yellow',
          light: '#ffb300',
        },
        info: {
          dark: 'orange',
          light: '#f4511e',
        },
        text: {
          dark: 'foreground',
          light: '#292d3e',
        },
        textMuted: {
          dark: 'comment',
          light: '#8796b0',
        },
        background: {
          dark: '#292d3e',
          light: '#fafafa',
        },
        backgroundPanel: {
          dark: '#1e2132',
          light: '#f5f5f5',
        },
        backgroundElement: {
          dark: '#32364a',
          light: '#e7e7e8',
        },
        syntaxFunction: {
          dark: 'blue',
          light: '#4976eb',
        },
      },
      defs: {
        background: '#292d3e',
        backgroundAlt: '#1e2132',
        backgroundPanel: '#32364a',
        foreground: '#a6accd',
        foregroundBright: '#bfc7d5',
        comment: '#676e95',
        red: '#f07178',
        orange: '#f78c6c',
        yellow: '#ffcb6b',
        green: '#c3e88d',
        cyan: '#89ddff',
        blue: '#82aaff',
        purple: '#c792ea',
        magenta: '#ff5370',
        pink: '#f07178',
      },
    },
    rosepine: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'foam',
          light: 'pine',
        },
        success: {
          dark: 'pine',
          light: '#286983',
        },
        error: {
          dark: 'love',
          light: '#b4637a',
        },
        warning: {
          dark: 'gold',
          light: '#ea9d34',
        },
        info: {
          dark: 'foam',
          light: '#56949f',
        },
        text: {
          dark: '#e0def4',
          light: '#575279',
        },
        textMuted: {
          dark: 'muted',
          light: 'dawnMuted',
        },
        background: {
          dark: 'base',
          light: 'dawnBase',
        },
        backgroundPanel: {
          dark: 'surface',
          light: 'dawnSurface',
        },
        backgroundElement: {
          dark: 'overlay',
          light: 'dawnOverlay',
        },
        syntaxFunction: {
          dark: 'rose',
          light: '#d7827e',
        },
      },
      defs: {
        base: '#191724',
        surface: '#1f1d2e',
        overlay: '#26233a',
        muted: '#6e6a86',
        subtle: '#908caa',
        text: '#e0def4',
        love: '#eb6f92',
        gold: '#f6c177',
        rose: '#ebbcba',
        pine: '#31748f',
        foam: '#9ccfd8',
        iris: '#c4a7e7',
        highlightLow: '#21202e',
        highlightMed: '#403d52',
        highlightHigh: '#524f67',
        moonBase: '#232136',
        moonSurface: '#2a273f',
        moonOverlay: '#393552',
        moonMuted: '#6e6a86',
        moonSubtle: '#908caa',
        moonText: '#e0def4',
        dawnBase: '#faf4ed',
        dawnSurface: '#fffaf3',
        dawnOverlay: '#f2e9e1',
        dawnMuted: '#9893a5',
        dawnSubtle: '#797593',
        dawnText: '#575279',
      },
    },
    solarized: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'blue',
          light: 'blue',
        },
        success: {
          dark: 'green',
          light: 'green',
        },
        error: {
          dark: 'red',
          light: 'red',
        },
        warning: {
          dark: 'yellow',
          light: 'yellow',
        },
        info: {
          dark: 'orange',
          light: 'orange',
        },
        text: {
          dark: 'base0',
          light: 'base00',
        },
        textMuted: {
          dark: 'base01',
          light: 'base1',
        },
        background: {
          dark: 'base03',
          light: 'base3',
        },
        backgroundPanel: {
          dark: 'base02',
          light: 'base2',
        },
        backgroundElement: {
          dark: '#073642',
          light: '#eee8d5',
        },
        syntaxFunction: {
          dark: 'blue',
          light: 'blue',
        },
      },
      defs: {
        base03: '#002b36',
        base02: '#073642',
        base01: '#586e75',
        base00: '#657b83',
        base0: '#839496',
        base1: '#93a1a1',
        base2: '#eee8d5',
        base3: '#fdf6e3',
        yellow: '#b58900',
        orange: '#cb4b16',
        red: '#dc322f',
        magenta: '#d33682',
        violet: '#6c71c4',
        blue: '#268bd2',
        cyan: '#2aa198',
        green: '#859900',
      },
    },
    synthwave84: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'cyan',
          light: '#00bcd4',
        },
        success: {
          dark: 'green',
          light: '#4caf50',
        },
        error: {
          dark: 'red',
          light: '#f44336',
        },
        warning: {
          dark: 'yellow',
          light: '#ff9800',
        },
        info: {
          dark: 'orange',
          light: '#ff5722',
        },
        text: {
          dark: 'foreground',
          light: '#262335',
        },
        textMuted: {
          dark: 'foregroundMuted',
          light: '#5c5c8a',
        },
        background: {
          dark: '#262335',
          light: '#fafafa',
        },
        backgroundPanel: {
          dark: '#1e1a29',
          light: '#f5f5f5',
        },
        backgroundElement: {
          dark: '#2a2139',
          light: '#eeeeee',
        },
        syntaxFunction: {
          dark: 'orange',
          light: '#ff5722',
        },
      },
      defs: {
        background: '#262335',
        backgroundAlt: '#1e1a29',
        backgroundPanel: '#2a2139',
        foreground: '#ffffff',
        foregroundMuted: '#848bbd',
        pink: '#ff7edb',
        pinkBright: '#ff92df',
        cyan: '#36f9f6',
        cyanBright: '#72f1f8',
        yellow: '#fede5d',
        yellowBright: '#fff95d',
        orange: '#ff8b39',
        orangeBright: '#ff9f43',
        purple: '#b084eb',
        purpleBright: '#c792ea',
        red: '#fe4450',
        redBright: '#ff5e5b',
        green: '#72f1b8',
        greenBright: '#97f1d8',
      },
    },
    tokyonight: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'darkStep9',
          light: 'lightStep9',
        },
        success: {
          dark: 'darkGreen',
          light: 'lightGreen',
        },
        error: {
          dark: 'darkRed',
          light: 'lightRed',
        },
        warning: {
          dark: 'darkOrange',
          light: 'lightOrange',
        },
        info: {
          dark: 'darkStep9',
          light: 'lightStep9',
        },
        text: {
          dark: 'darkStep12',
          light: 'lightStep12',
        },
        textMuted: {
          dark: 'darkStep11',
          light: 'lightStep11',
        },
        background: {
          dark: 'darkStep1',
          light: 'lightStep1',
        },
        backgroundPanel: {
          dark: 'darkStep2',
          light: 'lightStep2',
        },
        backgroundElement: {
          dark: 'darkStep3',
          light: 'lightStep3',
        },
        syntaxFunction: {
          dark: 'darkStep9',
          light: 'lightStep9',
        },
      },
      defs: {
        darkStep1: '#1a1b26',
        darkStep2: '#1e2030',
        darkStep3: '#222436',
        darkStep4: '#292e42',
        darkStep5: '#3b4261',
        darkStep6: '#545c7e',
        darkStep7: '#737aa2',
        darkStep8: '#9099b2',
        darkStep9: '#82aaff',
        darkStep10: '#89b4fa',
        darkStep11: '#828bb8',
        darkStep12: '#c8d3f5',
        darkRed: '#ff757f',
        darkOrange: '#ff966c',
        darkYellow: '#ffc777',
        darkGreen: '#c3e88d',
        darkCyan: '#86e1fc',
        darkPurple: '#c099ff',
        lightStep1: '#e1e2e7',
        lightStep2: '#d5d6db',
        lightStep3: '#c8c9ce',
        lightStep4: '#b9bac1',
        lightStep5: '#a8aecb',
        lightStep6: '#9699a8',
        lightStep7: '#737a8c',
        lightStep8: '#5a607d',
        lightStep9: '#2e7de9',
        lightStep10: '#1a6ce7',
        lightStep11: '#8990a3',
        lightStep12: '#3760bf',
        lightRed: '#f52a65',
        lightOrange: '#b15c00',
        lightYellow: '#8c6c3e',
        lightGreen: '#587539',
        lightCyan: '#007197',
        lightPurple: '#9854f1',
      },
    },
    vercel: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'blue700',
          light: 'blue700',
        },
        success: {
          dark: 'green700',
          light: '#388E3C',
        },
        error: {
          dark: 'red700',
          light: '#DC3545',
        },
        warning: {
          dark: 'amber700',
          light: '#FF9500',
        },
        info: {
          dark: 'blue900',
          light: 'blue700',
        },
        text: {
          dark: 'gray1000',
          light: 'lightGray1000',
        },
        textMuted: {
          dark: 'gray600',
          light: 'lightGray600',
        },
        background: {
          dark: 'background200',
          light: 'lightBackground',
        },
        backgroundPanel: {
          dark: 'gray100',
          light: 'lightGray100',
        },
        backgroundElement: {
          dark: 'gray300',
          light: 'lightGray200',
        },
        syntaxFunction: {
          dark: 'purple900',
          light: 'purple700',
        },
      },
      defs: {
        background100: '#0A0A0A',
        background200: '#000000',
        gray100: '#1A1A1A',
        gray200: '#1F1F1F',
        gray300: '#292929',
        gray400: '#2E2E2E',
        gray500: '#454545',
        gray600: '#878787',
        gray700: '#8F8F8F',
        gray900: '#A1A1A1',
        gray1000: '#EDEDED',
        blue600: '#0099FF',
        blue700: '#0070F3',
        blue900: '#52A8FF',
        blue1000: '#EBF8FF',
        red700: '#E5484D',
        red900: '#FF6166',
        red1000: '#FDECED',
        amber700: '#FFB224',
        amber900: '#F2A700',
        amber1000: '#FDF4DC',
        green700: '#46A758',
        green900: '#63C46D',
        green1000: '#E6F9E9',
        teal700: '#12A594',
        teal900: '#0AC7AC',
        purple700: '#8E4EC6',
        purple900: '#BF7AF0',
        pink700: '#E93D82',
        pink900: '#F75590',
        highlightPink: '#FF0080',
        highlightPurple: '#F81CE5',
        cyan: '#50E3C2',
        lightBackground: '#FFFFFF',
        lightGray100: '#FAFAFA',
        lightGray200: '#EAEAEA',
        lightGray600: '#666666',
        lightGray1000: '#171717',
      },
    },
    vesper: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: '#FFC799',
          light: '#FFC799',
        },
        success: {
          dark: 'vesperSuccess',
          light: 'vesperSuccess',
        },
        error: {
          dark: 'vesperError',
          light: 'vesperError',
        },
        warning: {
          dark: 'vesperWarning',
          light: 'vesperWarning',
        },
        info: {
          dark: '#FFC799',
          light: '#FFC799',
        },
        text: {
          dark: 'vesperFg',
          light: 'vesperBg',
        },
        textMuted: {
          dark: 'vesperMuted',
          light: 'vesperMuted',
        },
        background: {
          dark: 'vesperBg',
          light: '#FFF',
        },
        backgroundPanel: {
          dark: 'vesperBg',
          light: '#F0F0F0',
        },
        backgroundElement: {
          dark: 'vesperBg',
          light: '#E0E0E0',
        },
        syntaxFunction: {
          dark: 'vesperFunction',
          light: 'vesperFunction',
        },
      },
      defs: {
        vesperBg: '#101010',
        vesperFg: '#FFF',
        vesperComment: '#8b8b8b',
        vesperKeyword: '#A0A0A0',
        vesperFunction: '#FFC799',
        vesperString: '#99FFE4',
        vesperNumber: '#FFC799',
        vesperError: '#FF8080',
        vesperWarning: '#FFC799',
        vesperSuccess: '#99FFE4',
        vesperMuted: '#A0A0A0',
      },
    },
    zenburn: {
      $schema: 'https://opencode.ai/theme.json',
      theme: {
        primary: {
          dark: 'blue',
          light: '#5f7f8f',
        },
        success: {
          dark: 'green',
          light: '#5f8f5f',
        },
        error: {
          dark: 'red',
          light: '#8f5f5f',
        },
        warning: {
          dark: 'yellow',
          light: '#8f8f5f',
        },
        info: {
          dark: 'orange',
          light: '#8f7f5f',
        },
        text: {
          dark: 'fg',
          light: '#3f3f3f',
        },
        textMuted: {
          dark: 'fgMuted',
          light: '#6f6f6f',
        },
        background: {
          dark: 'bg',
          light: '#ffffef',
        },
        backgroundPanel: {
          dark: 'bgAlt',
          light: '#f5f5e5',
        },
        backgroundElement: {
          dark: 'bgPanel',
          light: '#ebebdb',
        },
        syntaxFunction: {
          dark: 'blue',
          light: '#5f7f8f',
        },
      },
      defs: {
        bg: '#3f3f3f',
        bgAlt: '#4f4f4f',
        bgPanel: '#5f5f5f',
        fg: '#dcdccc',
        fgMuted: '#9f9f9f',
        red: '#cc9393',
        redBright: '#dca3a3',
        green: '#7f9f7f',
        greenBright: '#8fb28f',
        yellow: '#f0dfaf',
        yellowDim: '#e0cf9f',
        blue: '#8cd0d3',
        blueDim: '#7cb8bb',
        magenta: '#dc8cc3',
        cyan: '#93e0e3',
        orange: '#dfaf8f',
      },
    },
  };
